dispatcher/urls.py
from django.conf.urls import url, patterns


urlpatterns = patterns(
    url(r'^(?P<dispatch_id>\w+)/$', 'dispatcher.views.dispatch'),
)

shortio/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'shortio.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'shorts.views.index'),
    url(r'^shorts/', include('shorts.urls', namespace='urls')),
    url(r'^api/', include('shorts.urls', namespace='api')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^(?P<dispatch_id>\w+)/$', 'dispatcher.views.dispatch'),
)

shorts/urls.py
from django.conf.urls import patterns, url, include
from shorts import views

from .api import UserList, UserDetail
from .api import UrlList, UrlDetail, UserUrlList

user_urls = patterns(
    '',
    url(r'^/(?P<username>[0-9a-zA-Z_-]+)/urlss$',
        UserUrlList.as_view(), name='userurl-list'),
    url(r'^/(?P<username>[0-9a-zA-Z_-]+)$',
        UserDetail.as_view(), name='user-detail'),
    url(r'^$', UserList.as_view(), name='user-list')
)

urls_urls = patterns(
    '',
    url(r'^/(?P<pk>\d+)$', UrlDetail.as_view(), name='urls-detail'),
    url(r'^$', UrlList.as_view(), name='urls-list')
)

urlpatterns = patterns(
    '',
    url(r'^users', include(user_urls)),
    url(r'^urls', include(urls_urls)),
    url(r'^$', views.index, name='index'),
    url(r'^create', views.create, name='create'),
    url(r'^(?P<url_id>\d+)/$', views.detail, name='detail')
)

dispatcher/models.py
from django.db import models

# Create your models here.

shorts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
from core import url
from shortio import settings


class User(AbstractUser):
    followers = models.ManyToManyField('self',
                                       related_name='followees',
                                       symmetrical=False)


class Url(models.Model):
    user = models.ForeignKey(User, related_name='user_urls', null=True, blank=True)
    url = models.CharField(max_length=2048)
    shortened_url = models.CharField(max_length=6)
    date_created = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.url

    def shorten_url(self):
        return "%s%s" % (settings.SIO_BASE_URL, url.dehydrate(self.id))

dispatcher/views.py
# Create your views here.
from django.http.response import Http404, HttpResponseRedirect
from core import url

from shorts.models import Url


def hello():
    print "Hello"


def dispatch(request, dispatch_id):
    try:
        u = Url.objects.get(pk=url.saturate(dispatch_id))
        return HttpResponseRedirect(u.url)
    except Url.DoesNotExist:
        raise Http404()

shorts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from models import Url
# Create your views here.


def index(request, error=None):
    latest_url_list = Url.objects.order_by('-date_created')[:5]
    context = {'latest_url_list': latest_url_list, 'error_message': error}
    return render(request, 'index.html', context)


def detail(request, url_id):
    url = get_object_or_404(Url, pk=url_id)
    return render(request, 'detail.html', {'url': url})


def create(request):
    try:
        u = Url(url=request.POST['url'])
        u.save()
    except Exception, ex:
        return index(request, error=ex.message)
    else:
        return HttpResponseRedirect(reverse('urls:index'))

shorts/templates/detail.html
{{ url }}

shorts/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'urls:create' %}" method="post">
        {% csrf_token %}
        <label for="url">Url: </label>
        <input type="text" id="url" name="url" value="">
        <input type="submit"/>
    </form>

    {% if error_message %}
        <h5>{{ error_message }}</h5>
    {% endif %}

    {% if latest_url_list %}
        <ul>
            {% for url in latest_url_list %}
                <li><a href="{% url 'urls:detail' url.id %}">{{ url.url }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

templates/base.html
{% load staticfiles %}
{% load urls_extras %}
{% load compress %}
<html>
<head>
    <title>ShortIO</title>
    {% compress css %}
        <link rel="stylesheet" type="text/css" href="{% static "themes/wed/css/bootstrap.min.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "themes/wed/snippet.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "themes/wed/snippet.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/site.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/font-awesome.css" %}">
    {% endcompress %}
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body ng-app="shortioApp" style="background-image: url('{% get_random_image %}');">
<div class="navbar-wrapper">
    <div class="container">
        <div class="navbar navbar-static-top pull-right">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    {% if user.is_authenticated %}
                        <li><a href="/logout">Logout</a></li>
                    {% else %}
                        <li><a href="/login">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    <!-- /container -->
</div>
<!-- /navbar wrapper -->
<div class="bootshape login-form">
    <div class="col-sm-6 col-md-5 col-lg-4 col-sm-offset-2 text-center login-popup-wrap">
        <div class="login-popup">
            <h1 class="title"><strong>ShortIO</strong></h1>
            <aside>all your shorts are belong to us</aside>
        </div>

        <div ng-include="'{% static "js/app/views/url.html" %}'"></div>

    </div>
</div>
{% compress js %}
    <script src="{% static "js/underscore/underscore.js" %}"></script>
    <script src="{% static "js/angular/angular.min.js" %}"></script>
    <script src="{% static "js/angular/angular-resource.min.js" %}"></script>
    <script src="{% static "js/zepto.js" %}"></script>
    <script src="{% static "js/script.js" %}"></script>

    <script src="{% static "js/app/app.js" %}"></script>
    <script src="{% static "js/app/directives/enter.js" %}"></script>
    <script src="{% static "js/app/controllers/url.js" %}"></script>
    <script src="{% static "js/app/services/url.js" %}"></script>
{% endcompress %}
</body>
</html>